kind: Service
apiVersion: v1
metadata:
  name: myfirstapp-service
  labels:
   app: myfirstapp
spec:
  selector:
    app: myfirstapp
  ports:
  - protocol: "TCP"
    port: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis