apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myfirstapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myfirstapp
    spec:
      containers:
      - name: myfirstapp
        image: torosent/myfirstapp
        ports:
        - containerPort: 80

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: library/redis
        ports:
        - containerPort: 6379
